### ISSUE TITLE
events-ruler 可能存在内存泄露问题

### ISSUE THREAD

**Issue by yangjinheng** [kubesphere/kube-events#19]
pkg/ruler/kube_events_ruler.go:218

在 goroutine 中使用闭包变量可能有问题。

**Comment by yangjinheng** [comment]
for _, evt := range evts {
    evt := evt
    if err := r.taskPool.Submit(func() {
        ....
    })
}

**Comment by junotx** [comment]
> ```go
> for _, evt := range evts {
>     evt := evt  // add
>     if err := r.taskPool.Submit(func() {
>         ....
>     })
> }
> ```

Yes, here needs fixing up, which will be done later, and also welcome you to submit pr to fix that @yangjinheng
