### ISSUE TITLE
remove hostPath mounts

### ISSUE THREAD

**Issue by ctrought** [kubesphere/kube-events#35]
Nice project, glad I came across it!

I've used helm install method, out of box the deployments will fail on OCP because hostPath mounts require elevated privileges. Perhaps the TZ could instead be set by environment variable and configured via helm values so that the user can configure if desired.

**Comment by junotx** [comment]
@ctrought 
Yea, thanks for your reporting and your solution suggestion good for me.
You're welcome to create a PR for this if you're insterested

**Comment by ctrought** [comment]
Completed in #37
