### ISSUE TITLE
有在 Grafana 展示 Event 告警列表的模版吗？

### ISSUE THREAD

**Issue by gasxia** [kubesphere/kube-events#4]
在做同样的项目，准备调研实践下后切换到这个项目来。

想问下 Event 告警列表是在哪里展示的呢？  

如果是在 Grafana 有配套的模版提供吗？

**Comment by benjaminhuo** [comment]
event 告警是发到 Alertmanager 的，Alertmanager web UI 可看

**Comment by benjaminhuo** [comment]
有问题可以来我们 [Slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) 沟通， #sig-observability

**Comment by gasxia** [comment]
ok, 已加
