### ISSUE TITLE
outdated replace usage in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [kubesphere/kube-events#45]
There is a replace line in go.mod pinning `golang.org/x/text` to `v0.3.7`. However, according to [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059), version of `golang.org/x/text` before `v0.3.8` suffers potential vulnerability. Should it be updated? <br>
<https://github.com/kubesphere/kube-events/blob/master/go.mod#L126>
```txt
golang.org/x/text => golang.org/x/text v0.3.7
```
Or you may update some direct dependency, say `k8s.io/client-go`. It will indirectly update the version of `golang.org/x/text` and then the above replace line can be dropped.
```txt
$ go mod why -m golang.org/x/text
# golang.org/x/text
github.com/kubesphere/kube-events/pkg/ruler
k8s.io/client-go/rest
golang.org/x/net/http2
golang.org/x/net/idna
golang.org/x/text/secure/bidirule
```

**Comment by junotx** [comment]
Thanks. It should be updated. If you have a pr about it, welcome
