### ISSUE TITLE
Rule 的 condition 配置支持正则匹配吗？

### ISSUE THREAD

**Issue by gasxia** [kubesphere/kube-events#6]
event 数据属性里关键信息主要在 message 里，如果只是针对 reason 类型告警的话，比较容易误报。  

当发现误报了之后，只能对 message 加更严格的条件了，message 的内容完全是自定义的，只能通过正则匹配来过滤了。

现在有实现这个功能吗？

或者说有更好的解决方案吗？

**Comment by benjaminhuo** [comment]
@junotx Do we support regex match for message? Is it possible to add this?

**Comment by junotx** [comment]
It is not currently supported, you can use `contains` instead, e.g. `event.message contains "error"`. And you can get supported grammars from [here](https://github.com/kubesphere/kube-events/blob/master/pkg/ruler/visitor/parser/EventRule.tokens)

**Comment by benjaminhuo** [comment]
@gasxia operator `contains` can meet some of your requirements, we can add regex support in the future if the requirements is strong.

**Comment by wanjunlei** [comment]
@junotx @benjaminhuo you can take a look at this, https://github.com/wanjunlei/event-rule-engine

**Comment by benjaminhuo** [comment]
> @junotx @benjaminhuo you can take a look at this, https://github.com/wanjunlei/event-rule-engine

That's great!

**Comment by benjaminhuo** [comment]
@gasxia we'll add regex match for message to kube-events soon
